### PR TITLE
build on OSX 10.11.6 El Capitan

### PR DESCRIPTION
**Pull request by glycerine**
Tried to build on OSX 10.11.6 El Capitan, got:
```
~/go/src/github.com/Morgan-Stanley/hobbes (master) $ make
Scanning dependencies of target hobbes
[  0%] Building CXX object CMakeFiles/hobbes.dir/lib/hobbes/boot/gen/boot.C.o
[  1%] Building CXX object CMakeFiles/hobbes.dir/lib/hobbes/db/bindings.C.o
[  1%] Building CXX object CMakeFiles/hobbes.dir/lib/hobbes/db/file.C.o
[  2%] Building CXX object CMakeFiles/hobbes.dir/lib/hobbes/db/series.C.o
In file included from /Users/me/go/src/github.com/Morgan-Stanley/hobbes/lib/hobbes/db/series.C:2:
In file included from /Users/me/go/src/github.com/Morgan-Stanley/hobbes/include/hobbes/db/series.H:12:
/Users/me/go/src/github.com/Morgan-Stanley/hobbes/include/hobbes/util/perf.H:15:21: error: 
      use of undeclared identifier 'CLOCK_MONOTONIC'
  if (clock_gettime(CLOCK_MONOTONIC, &ts) == 0) {
                    ^
/Users/me/go/src/github.com/Morgan-Stanley/hobbes/include/hobbes/util/perf.H:25:21: error: 
      use of undeclared identifier 'CLOCK_REALTIME'
  if (clock_gettime(CLOCK_REALTIME, &ts) == 0) {
                    ^
2 errors generated.
make[2]: *** [CMakeFiles/hobbes.dir/lib/hobbes/db/series.C.o] Error 1
make[1]: *** [CMakeFiles/hobbes.dir/all] Error 2
make: *** [all] Error 2
~/go/src/github.com/Morgan-Stanley/hobbes (master) $ make

```

Accordingly to this stackoverflow question, El Capitan doesn't have clock_gettime() implemented:

https://stackoverflow.com/questions/5167269/clock-gettime-alternative-in-mac-os-x

Hence this PR provides code from the following repo as suggested by the above stackoverflow answer; this allows hobbes to build on OSX El Capitan, using `LLVM_DIR=/usr/local/opt/llvm@3.7/lib/llvm-3.7/share/llvm/cmake/ cmake .` as suggested in #27. 

https://github.com/ChisholmKyle/PosixMachTiming

### CODE REVIEW

**Comment by kthielen** [comment]
Thanks for submitting a pull request! :)

This explains the reports I've heard from some other folks that their OSX builds failed with this error.  I've just been building hobbes on OSX 10.12.5 (Sierra) and so haven't hit this.

Does this change also resolve your problem with the asyncClientAPI test deadlock?

There are a few issues that are blocking me from accepting this PR.  One is that it fails to build on OSX 10.12.5 (there's a "Travis CI" build step there that has failed and you can see details by clicking on the "Details" link).  Another is that it looks like some of this code comes from another person's repo (unless you are ChisholmKyle) and there's a copyright/license there that I'm not sure is compatible with this project.  Finally we also have an internal requirement to get from every unique contributor a signed document stating that their contributions are their own and don't belong to their employer (just have to protect ourselves legally).

This is great that you've identified the source of this problem and have something that resolves it.  One way or another, this will get addressed now.

**Comment by glycerine** [comment]
> Does this change also resolve your problem with the asyncClientAPI test deadlock?

Yes. The latest version of the PR fixes that livelock; it was simply that the initializing function wasn't being called. So time() was always returning 0. I added a global class instance now that does the necessary init.

> One is that it fails to build on OSX 10.12.5 

Yeah, I suspected it might. So clock_gettime() newly already available on OSX Sierra/ 10.12. I'm sure there's a way to `#ifdef` so that the definition of clock_gettime() and its constants only are made available to OSX 10.11.6/El Capitan, but I didn't locate it after a quick google search. Should be an easy fix if somebody can figure out the proper ifdef for clang.

> Another is that it looks like some of this code comes from another person's 

The code is from the github repo cited, and is copyrighted by Kyle Chisholm, as it says at the top of the file. It is licensed under the license that is included at the top of both the .h and .c file, per the license's requirements. The ISC is a very permissive license, and appears fully compatible with the more restrictive Apache 2.

> requirement to get from every unique contributor a signed document

my contribution is pretty darn minor, but I don't mind doing a  CLA if you can provide a link to it.

**Comment by kthielen** [comment]
That's very interesting about the time=0 discovery you made, it's news to me.

I agree that the contribution is minor but the lawyers are pretty hard-headed about it.  I will see if I can upload the doc today.  :)

In the meantime I will have to look into how to discriminate between OSX versions in the preprocessor.

**Comment by glycerine** [comment]
> That's very interesting about the time=0 discovery you made, it's news to me.

Of course that comment only applies to the implementation of clock_gettime() provided in this PR; it needed this init line in particular. https://github.com/Morgan-Stanley/hobbes/pull/29/files#diff-d1507029cb31f6be1c345e61de7b445dR69

> I agree that the contribution is minor but the lawyers are pretty hard-headed about it. I will see if I can upload the doc today. :)

They probably don't know that the code submitted is already licensed under the ISC license. For avoidance of doubt, I added my name to the copyright, so that the license applies to my contribution as well. 

The latest should compile on Sierra again, and those wanting to build on El Capitan will need to pass -DMAC_OS_X_VERSION_10_11 to the compiler manually for now.

**Comment by glycerine** [comment]
yay. Travis likes this, all checks passed.

**Comment by kthielen** [comment]
Sorry for the delay in getting back to you.  There's some internal discussion about the PR acceptance process and making it less onerous.  I want to get this change in the meantime to get hobbes working on earlier versions of OSX.  Currently I'm trying to see if/how I can get Travis CI to do a build on an earlier OSX to verify.

**Comment by kthielen** [comment]
OK, while the PR policy discussions are taking place, I've at least got this PR that addresses your findings and also configures Travis-CI to test OSX 10.12 w/ xcode8.3 and also 10.11 w/ xcode8 (versions of xcode prior to 8 don't work due to usage of 'thread_local'):

https://github.com/Morgan-Stanley/hobbes/pull/38

Hopefully this should resolve this issue for everyone.

**Comment by kthielen** [comment]
Thank you for raising this issue and providing a fix.  I've updated our Travis CI config to build with xcode8 on OSX El Capitan and merged a change that corrects this issue.
