### ISSUE TITLE
Build fails on ignored return value

### ISSUE THREAD

**Issue by thmzlt** [Morgan-Stanley/hobbes#318]
I'm stuck building hobbes outside of the Ubuntu Linux CI environment. I'm also running Linux but using the [Nix](https://nixos.org/nix/) package manager. Nix builds software in isolate which helps with reliability and reproducibility. It's available on Linux and macOS.

I can test multiple combinations of GCC and LLVM versions in Nix, but most of them fail on `db/signals.C` where a return vaule is being ignored according to the compiler. Here is the verbose output for GCC 5.5 and LLVM 3.5:

```
these derivations will be built:
  /nix/store/qyvypzxa995560zgccn2r07f1d9psmm5-hobbes.drv
building '/nix/store/qyvypzxa995560zgccn2r07f1d9psmm5-hobbes.drv'...
unpacking sources
unpacking source archive /nix/store/j2wn47ky8zb1lnxvgagp4f58zfqs65ia-hobbes
source root is hobbes
patching sources
configuring
Re-run cmake no build system arguments
-- The C compiler identification is GNU 5.5.0
-- The CXX compiler identification is GNU 5.5.0
-- Check for working C compiler: /nix/store/6ivqy3cygxpn3nbwm6isx80hgcbk2dh6-gcc-wrapper-5.5.0/bin/gcc
-- Check for working C compiler: /nix/store/6ivqy3cygxpn3nbwm6isx80hgcbk2dh6-gcc-wrapper-5.5.0/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /nix/store/6ivqy3cygxpn3nbwm6isx80hgcbk2dh6-gcc-wrapper-5.5.0/bin/g++
-- Check for working CXX compiler: /nix/store/6ivqy3cygxpn3nbwm6isx80hgcbk2dh6-gcc-wrapper-5.5.0/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found ZLIB: /nix/store/ylpi31dwsgm9c9rndp0j5b4na749d97z-zlib-1.2.11/lib/libz.so (found version "1.2.11")
-- Found readline: /nix/store/y5w0ifg4kqskzqx958bhyhqcdfglzfrq-readline-6.3p08-dev/include
-- Looking for cbreak in /nix/store/3cz3xgnghkpy41ab9hcj7011sqbrpg4n-ncurses-6.1-20190112/lib/libncurses.so
-- Looking for cbreak in /nix/store/3cz3xgnghkpy41ab9hcj7011sqbrpg4n-ncurses-6.1-20190112/lib/libncurses.so - found
-- Found Curses: /nix/store/3cz3xgnghkpy41ab9hcj7011sqbrpg4n-ncurses-6.1-20190112/lib/libncurses.so
-- llvm libs: /nix/store/gpla85b2p4y6lk0dvwywcl5xahpjimzx-llvm-3.5.2/lib/libLLVMJIT.so /nix/store/gpla85b2p4y6lk0dvwywcl5xahpjimzx-llvm-3.5.2/lib/libLLVMExecutionEngine.so /nix/store/gpla85b2p4y6lk0dvwywcl5xahpjimzx-llvm-3.5.2/lib/libLLVMipo.so /nix/store/gpla85b2p4y6lk0dvwywcl5xahpjimzx-llvm-3.5.2/lib/libLLVMVectorize.so /nix/store/gpla85b2p4y6lk0dvwywcl5xahpjimzx-llvm-3.5.2/lib/libLLVMX86Disassembler.so /nix/store/gpla85b2p4y6lk0dvwywcl5xahpjimzx-llvm-3.5.2/lib/libLLVMX86AsmParser.so /nix/store/gpla85b2p4y6lk0dvwywcl5xahpjimzx-llvm-3.5.2/lib/libLLVMX86CodeGen.so /nix/store/gpla85b2p4y6lk0dvwywcl5xahpjimzx-llvm-3.5.2/lib/libLLVMSelectionDAG.so /nix/store/gpla85b2p4y6lk0dvwywcl5xahpjimzx-llvm-3.5.2/lib/libLLVMAsmPrinter.so /nix/store/gpla85b2p4y6lk0dvwywcl5xahpjimzx-llvm-3.5.2/lib/libLLVMCodeGen.so /nix/store/gpla85b2p4y6lk0dvwywcl5xahpjimzx-llvm-3.5.2/lib/libLLVMScalarOpts.so /nix/store/gpla85b2p4y6lk0dvwywcl5xahpjimzx-llvm-3.5.2/lib/libLLVMInstCombine.so /nix/store/gpla85b2p4y6lk0dvwywcl5xahpjimzx-llvm-3.5.2/lib/libLLVMTransformUtils.so /nix/store/gpla85b2p4y6lk0dvwywcl5xahpjimzx-llvm-3.5.2/lib/libLLVMipa.so /nix/store/gpla85b2p4y6lk0dvwywcl5xahpjimzx-llvm-3.5.2/lib/libLLVMAnalysis.so /nix/store/gpla85b2p4y6lk0dvwywcl5xahpjimzx-llvm-3.5.2/lib/libLLVMTarget.so /nix/store/gpla85b2p4y6lk0dvwywcl5xahpjimzx-llvm-3.5.2/lib/libLLVMX86Desc.so /nix/store/gpla85b2p4y6lk0dvwywcl5xahpjimzx-llvm-3.5.2/lib/libLLVMObject.so /nix/store/gpla85b2p4y6lk0dvwywcl5xahpjimzx-llvm-3.5.2/lib/libLLVMMCParser.so /nix/store/gpla85b2p4y6lk0dvwywcl5xahpjimzx-llvm-3.5.2/lib/libLLVMBitReader.so /nix/store/gpla85b2p4y6lk0dvwywcl5xahpjimzx-llvm-3.5.2/lib/libLLVMCore.so /nix/store/gpla85b2p4y6lk0dvwywcl5xahpjimzx-llvm-3.5.2/lib/libLLVMX86Info.so /nix/store/gpla85b2p4y6lk0dvwywcl5xahpjimzx-llvm-3.5.2/lib/libLLVMX86AsmPrinter.so /nix/store/gpla85b2p4y6lk0dvwywcl5xahpjimzx-llvm-3.5.2/lib/libLLVMMC.so /nix/store/gpla85b2p4y6lk0dvwywcl5xahpjimzx-llvm-3.5.2/lib/libLLVMX86Utils.so /nix/store/gpla85b2p4y6lk0dvwywcl5xahpjimzx-llvm-3.5.2/lib/libLLVMSupport.so
-- llvm ldflags: -L/nix/store/gpla85b2p4y6lk0dvwywcl5xahpjimzx-llvm-3.5.2/lib
-- llvm syslibs: -lrt -ldl -ltinfo -lpthread -lz
-- Found PythonInterp: /nix/store/gk0lrrvqz491xn0mgrshzgvazx4rghl2-python-2.7.17/bin/python (found version "2.7.17")
-- Configuring done
-- Generating done
-- Build files have been written to: /build/hobbes
building
build flags: SHELL=/nix/store/xb062l4b76zyhq6grqf4iyfdikkpg8fl-bash-4.4-p23/bin/bash
/nix/store/af4js9rv5cnxs0ig0vfqbb0arh2n0bfy-cmake-3.15.5/bin/cmake -S/build/hobbes -B/build/hobbes --check-build-system CMakeFiles/Makefile.cmake 0
/nix/store/af4js9rv5cnxs0ig0vfqbb0arh2n0bfy-cmake-3.15.5/bin/cmake -E cmake_progress_start /build/hobbes/CMakeFiles /build/hobbes/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/build/hobbes'
make -f CMakeFiles/hobbes-pic.dir/build.make CMakeFiles/hobbes-pic.dir/depend
make[2]: Entering directory '/build/hobbes'
cd /build/hobbes && /nix/store/af4js9rv5cnxs0ig0vfqbb0arh2n0bfy-cmake-3.15.5/bin/cmake -E cmake_depends "Unix Makefiles" /build/hobbes /build/hobbes /build/hobbes /build/hobbes /build/hobbes/CMakeFiles/hobbes-pic.dir/DependInfo.cmake --color=
Dependee "/build/hobbes/CMakeFiles/hobbes-pic.dir/DependInfo.cmake" is newer than depender "/build/hobbes/CMakeFiles/hobbes-pic.dir/depend.internal".
Dependee "/build/hobbes/CMakeFiles/CMakeDirectoryInformation.cmake" is newer than depender "/build/hobbes/CMakeFiles/hobbes-pic.dir/depend.internal".
Scanning dependencies of target hobbes-pic
make[2]: Leaving directory '/build/hobbes'
make -f CMakeFiles/hobbes-pic.dir/build.make CMakeFiles/hobbes-pic.dir/build
make[2]: Entering directory '/build/hobbes'
[  0%] Building CXX object CMakeFiles/hobbes-pic.dir/lib/hobbes/boot/gen/boot.C.o
/nix/store/6ivqy3cygxpn3nbwm6isx80hgcbk2dh6-gcc-wrapper-5.5.0/bin/g++  -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -I/build/hobbes/include  -Werror=old-style-cast -Werror -Wall -Wextra -Winit-self -Wreturn-type -Wunused-variable -Wsign-compare -Warray-bounds -Wunknown-pragmas -Wuninitialized -Wstrict-aliasing -Wunused-value -Wunused-label -Wswitch -Wcast-align -Wctor-dtor-privacy -Wmissing-noreturn -Wunused-parameter -Wreorder -fPIC   -std=gnu++11 -o CMakeFiles/hobbes-pic.dir/lib/hobbes/boot/gen/boot.C.o -c /build/hobbes/lib/hobbes/boot/gen/boot.C
[  1%] Building CXX object CMakeFiles/hobbes-pic.dir/lib/hobbes/db/bindings.C.o
/nix/store/6ivqy3cygxpn3nbwm6isx80hgcbk2dh6-gcc-wrapper-5.5.0/bin/g++  -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -I/build/hobbes/include  -Werror=old-style-cast -Werror -Wall -Wextra -Winit-self -Wreturn-type -Wunused-variable -Wsign-compare -Warray-bounds -Wunknown-pragmas -Wuninitialized -Wstrict-aliasing -Wunused-value -Wunused-label -Wswitch -Wcast-align -Wctor-dtor-privacy -Wmissing-noreturn -Wunused-parameter -Wreorder -fPIC   -std=gnu++11 -o CMakeFiles/hobbes-pic.dir/lib/hobbes/db/bindings.C.o -c /build/hobbes/lib/hobbes/db/bindings.C
[  1%] Building CXX object CMakeFiles/hobbes-pic.dir/lib/hobbes/db/cbindings.C.o
/nix/store/6ivqy3cygxpn3nbwm6isx80hgcbk2dh6-gcc-wrapper-5.5.0/bin/g++  -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -I/build/hobbes/include  -Werror=old-style-cast -Werror -Wall -Wextra -Winit-self -Wreturn-type -Wunused-variable -Wsign-compare -Warray-bounds -Wunknown-pragmas -Wuninitialized -Wstrict-aliasing -Wunused-value -Wunused-label -Wswitch -Wcast-align -Wctor-dtor-privacy -Wmissing-noreturn -Wunused-parameter -Wreorder -fPIC   -std=gnu++11 -o CMakeFiles/hobbes-pic.dir/lib/hobbes/db/cbindings.C.o -c /build/hobbes/lib/hobbes/db/cbindings.C
[  2%] Building CXX object CMakeFiles/hobbes-pic.dir/lib/hobbes/db/file.C.o
/nix/store/6ivqy3cygxpn3nbwm6isx80hgcbk2dh6-gcc-wrapper-5.5.0/bin/g++  -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -I/build/hobbes/include  -Werror=old-style-cast -Werror -Wall -Wextra -Winit-self -Wreturn-type -Wunused-variable -Wsign-compare -Warray-bounds -Wunknown-pragmas -Wuninitialized -Wstrict-aliasing -Wunused-value -Wunused-label -Wswitch -Wcast-align -Wctor-dtor-privacy -Wmissing-noreturn -Wunused-parameter -Wreorder -fPIC   -std=gnu++11 -o CMakeFiles/hobbes-pic.dir/lib/hobbes/db/file.C.o -c /build/hobbes/lib/hobbes/db/file.C
[  2%] Building CXX object CMakeFiles/hobbes-pic.dir/lib/hobbes/db/series.C.o
/nix/store/6ivqy3cygxpn3nbwm6isx80hgcbk2dh6-gcc-wrapper-5.5.0/bin/g++  -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -I/build/hobbes/include  -Werror=old-style-cast -Werror -Wall -Wextra -Winit-self -Wreturn-type -Wunused-variable -Wsign-compare -Warray-bounds -Wunknown-pragmas -Wuninitialized -Wstrict-aliasing -Wunused-value -Wunused-label -Wswitch -Wcast-align -Wctor-dtor-privacy -Wmissing-noreturn -Wunused-parameter -Wreorder -fPIC   -std=gnu++11 -o CMakeFiles/hobbes-pic.dir/lib/hobbes/db/series.C.o -c /build/hobbes/lib/hobbes/db/series.C
[  3%] Building CXX object CMakeFiles/hobbes-pic.dir/lib/hobbes/db/signals.C.o
/nix/store/6ivqy3cygxpn3nbwm6isx80hgcbk2dh6-gcc-wrapper-5.5.0/bin/g++  -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -I/build/hobbes/include  -Werror=old-style-cast -Werror -Wall -Wextra -Winit-self -Wreturn-type -Wunused-variable -Wsign-compare -Warray-bounds -Wunknown-pragmas -Wuninitialized -Wstrict-aliasing -Wunused-value -Wunused-label -Wswitch -Wcast-align -Wctor-dtor-privacy -Wmissing-noreturn -Wunused-parameter -Wreorder -fPIC   -std=gnu++11 -o CMakeFiles/hobbes-pic.dir/lib/hobbes/db/signals.C.o -c /build/hobbes/lib/hobbes/db/signals.C
/build/hobbes/lib/hobbes/db/signals.C: In lambda function:
/build/hobbes/lib/hobbes/db/signals.C:105:47: error: ignoring return value of 'ssize_t read(int, void*, size_t)', declared with attribute warn_unused_result [-Werror=unused-result]
         read(fd, event, sizeof(inotify_event));
                                               ^
/build/hobbes/lib/hobbes/db/signals.C:107:44: error: ignoring return value of 'ssize_t read(int, void*, size_t)', declared with attribute warn_unused_result [-Werror=unused-result]
           read(fd, event->name, event->len);
                                            ^
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/hobbes-pic.dir/build.make:128: CMakeFiles/hobbes-pic.dir/lib/hobbes/db/signals.C.o] Error 1
make[2]: Leaving directory '/build/hobbes'
make[1]: *** [CMakeFiles/Makefile2:80: CMakeFiles/hobbes-pic.dir/all] Error 2
make[1]: Leaving directory '/build/hobbes'
make: *** [Makefile:141: all] Error 2
builder for '/nix/store/qyvypzxa995560zgccn2r07f1d9psmm5-hobbes.drv' failed with exit code 2
error: build of '/nix/store/qyvypzxa995560zgccn2r07f1d9psmm5-hobbes.drv' failed
```

For those interested, this is the Nix derivation I'm using to build hobbes:

```nix
{ pkgs ? import (fetchTarball https://github.com/nixos/nixpkgs-channels/archive/nixos-unstable.tar.gz) {} }:

pkgs.stdenv.mkDerivation {
  name = "hobbes";
  src = ./.;

  nativeBuildInputs = with pkgs; [
    cmake
    gcc5
    llvm_35
    ncurses
    python27
    readline
    zlib
  ];

  configurePhase = ''
    cmake .
  '';

  VERBOSE = "1";
}
```

You can install Nix, add the contents above as a `default.nix` file in the root of the project, and then run **`nix-build`**.

If you can point me in the right direction, I'll be more than happy to contribute with a fix. I'm currently using hobbes inside a docker container running Ubuntu which is not ideal.

**Comment by kthielen** [comment]
Huh that's interesting, can I get hobbes through nixos?  I don't see it on the nixos.org website but I'd like to figure out how to get it there (it would make it easier to get for some folks I know who use nix).  Maybe I can try the derivation that you offered.

I see that the issue that you found happens where we read from the inotify FD without checking a return value (not sure if it's reasonable to expect that this case can't fail).

I can put up a PR to fix this, or if you want it should be enough to wrap those two cited read calls in `static_cast<void>()` (per this: https://stackoverflow.com/questions/53581744/how-can-i-intentionally-discard-a-nodiscard-return-value).

**Comment by thmzlt** [comment]
> Huh that's interesting, can I get hobbes through nixos?

If we can get the derivation from the other comment to build, I can open a PR to [nixos/nixpkgs](https://github.com/nixos/nixpkgs) so people can get hobbes straight from there.

> I can put up a PR to fix this, or if you want it should be enough to wrap those two cited read calls in static_cast<void>()

I tried the suggestion from that SO question before but it seems to have no effect:

```
[  3%] Building CXX object CMakeFiles/hobbes-pic.dir/lib/hobbes/db/signals.C.o
/nix/store/6ivqy3cygxpn3nbwm6isx80hgcbk2dh6-gcc-wrapper-5.5.0/bin/g++  -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -I/build/hobbes/include  -Werror=old-style-cast -Werror -Wall -Wextra -W
init-self -Wreturn-type -Wunused-variable -Wsign-compare -Warray-bounds -Wunknown-pragmas -Wuninitialized -Wstrict-aliasing -Wunused-value -Wunused-label -Wswitch -Wcast-align -Wctor-dtor-pr
ivacy -Wmissing-noreturn -Wunused-parameter -Wreorder -fPIC   -std=gnu++11 -o CMakeFiles/hobbes-pic.dir/lib/hobbes/db/signals.C.o -c /build/hobbes/lib/hobbes/db/signals.C
/build/hobbes/lib/hobbes/db/signals.C: In lambda function:
/build/hobbes/lib/hobbes/db/signals.C:105:66: error: ignoring return value of 'ssize_t read(int, void*, size_t)', declared with attribute warn_unused_result [-Werror=unused-result]
         static_cast<void>(read(fd, event, sizeof(inotify_event)));
                                                                  ^
/build/hobbes/lib/hobbes/db/signals.C:107:63: error: ignoring return value of 'ssize_t read(int, void*, size_t)', declared with attribute warn_unused_result [-Werror=unused-result]
           static_cast<void>(read(fd, event->name, event->len));
```

**Comment by kthielen** [comment]
It looks like this setting is quietly ignored on macOS (where I've been doing some testing today).  I've opened this PR (https://github.com/Morgan-Stanley/hobbes/pull/319) where I've turned on this flag so that we will always build with it going forward.  Once I see that the test fails to build as expected, I can verify a fix.

Thank you for bringing this up, also it'll be really interesting if we can get this into nixos!

**Comment by thmzlt** [comment]
Weird that the build passed even with the flag.

**Comment by kthielen** [comment]
I must not have done what I thought I was doing, but since you've found the problem I'm sure there's some way to get there eventually, maybe just need another few flags you've helpfully quoted above.  :)

**Comment by kthielen** [comment]
Ah ha, I think (according to this: https://stackoverflow.com/questions/2870529/g-how-to-get-warning-on-ignoring-function-return-value) that this warning only applies to functions with the attribute "__attribute__((warn_unused_result))" on their declaration.  I tested this with clang on macOS and confirmed that this was enough to get me the warning.

It might be that gcc 5.5 puts this attribute on the declaration for read (where otherwise it hasn't been set, so we haven't hit this before -- I guess this warning is implied by -Wall already).

I'll see if I can set up our CI to also build with gcc 5.5.  Ideally I'd like to reproduce the problem in an automated way before putting in a fix.

**Comment by thmzlt** [comment]
For the record, I have just tried building with gcc 4.8.5 in NixOS with no luck:

```
[  3%] Building CXX object CMakeFiles/hobbes.dir/lib/hobbes/db/signals.C.o
/nix/store/9x75fwzpi04zv0f5xjfsdll7cndwbj1j-gcc-wrapper-4.8.5/bin/g++  -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -I/build/hobbes/include  -Werror=old-style-cast -Werror -Wall -Wextra -W
init-self -Wreturn-type -Wunused-variable -Wsign-compare -Warray-bounds -Wunknown-pragmas -Wuninitialized -Wstrict-aliasing -Wunused-value -Wunused-label -Wswitch -Wcast-align -Wctor-dtor-pr
ivacy -Wmissing-noreturn -Wunused-parameter -Wreorder   -std=gnu++11 -o CMakeFiles/hobbes.dir/lib/hobbes/db/signals.C.o -c /build/hobbes/lib/hobbes/db/signals.C
/build/hobbes/lib/hobbes/db/signals.C: In lambda function:
/build/hobbes/lib/hobbes/db/signals.C:105:47: error: ignoring return value of 'ssize_t read(int, void*, size_t)', declared with attribute warn_unused_result [-Werror=unused-result]
         read(fd, event, sizeof(inotify_event));
                                               ^
/build/hobbes/lib/hobbes/db/signals.C:107:44: error: ignoring return value of 'ssize_t read(int, void*, size_t)', declared with attribute warn_unused_result [-Werror=unused-result]
           read(fd, event->name, event->len);
                                            ^
cc1plus: all warnings being treated as errors
```

**Comment by kthielen** [comment]
I've been working on getting nixos working on my laptop, seems that a recent macOS update made the install process much more complicated:

https://github.com/NixOS/nix/issues/2925

I'm not sure if I can get travis-ci to do this but I'm going to at least try reproducing this problem myself.

**Comment by thmzlt** [comment]
Damn!

I use Nix across other projects and I have successfully set it up with GitLab and CircleCI. I'll give Travis a try later today and let you know.

**Comment by kthielen** [comment]
I think that this nix script might not work on macOS:

```
$ nix-build
unpacking 'https://github.com/nixos/nixpkgs-channels/archive/nixos-unstable.tar.gz'...
error: Package ‘gcc-wrapper-5.5.0’ in /nix/store/x23j93xd3kd6hxw4vyacbjs73gswdgpi-source/pkgs/build-support/cc-wrapper/default.nix:384 is not supported on ‘x86_64-darwin’, refusing to evaluate.
```

Maybe I can put a Linux distro in a VM on my laptop, might as well.  What distro are you using to test this?

Also FWIW, in my little test program where I reproduced this error, it seemed that the `static_cast<void>()` was enough to resolve it.

At the end of this we're going to have a really small, simple fix.  :D

**Comment by thmzlt** [comment]
> Maybe I can put a Linux distro in a VM on my laptop, might as well. What distro are you using to test this?

I'm using [NixOS](https://nixos.org.nixos), but any Linux distro should do it. NixOS has a "LiveCD" image so you might not even need to install it on the disk (the installation process is a bit manual).

> Also FWIW, in my little test program where I reproduced this error, it seemed that the static_cast<void>() was enough to resolve it.

Right. I suspect Nix is doing something to the compiler, but I can't see it. Which versions of GCC/LLVM do you have on macOS?

**Comment by kthielen** [comment]
I have been downloading and installing CentOS in a VM in the background, took a while.  Now with your nix script, I've finally reproduced the same problem that you hit.  I can at least verify a fix locally, will leave the nix integration with travis-ci for a later date (I would like to figure out this nix stuff though, I know it's useful).

**Comment by thmzlt** [comment]
Sounds good. I'll work on the Nix integration with Travis.

**Comment by kthielen** [comment]
OK, there were a couple of similar cases after that one, so I followed it through to the end in this PR: https://github.com/Morgan-Stanley/hobbes/pull/319

I'm not sure if you can pull that branch, but now it has some kind of complaint about linking all of the LLVM libraries.  I wonder if the nix script should be changed somehow (I've just blindly copy/pasted it to run with `nix-build`).

**Comment by kthielen** [comment]
BTW, my change actually uses the return values in these cases to assert in case nothing is read/written.  These cases would have nothing to do with a failure (e.g. reading the inotify event data in the case of reacting to structured data file updates), so it's not such a big deal one way or the other (except it can't build down this path otherwise).

I found a funny thread on the `static_cast<void>()` failure to work around this problem in gcc: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=25509

**Comment by thmzlt** [comment]
> OK, there were a couple of similar cases after that one, so I followed it through to the end in this PR: #319

Tried building your branch and it went further but stopped at some more unused result errors: 

```
[ 98%] Building CXX object CMakeFiles/hog.dir/bin/hog/recovery.C.o
/nix/store/idmgv1qdd5hv81xqff45nlxzvjgvrq42-gcc-wrapper-5.5.0/bin/g++  -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -I/build/hobbes/include  -Werror=old-style-cast -Werror -Wall -Wextra -Winit-self -Wreturn-type -Wunused-variable -Wsign-compare -Warray-bounds -Wunknown-pragmas -Wuninitialized -Wstrict-aliasing -Wunused-value -Wunused-label -Wswitch -Wcast-align -Wctor-dtor-privacy -Wmissing-noreturn -Wunused-parameter -Wreorder   -std=gnu++11 -o CMakeFiles/hog.dir/bin/hog/config.C.o -c /build/hobbes/bin/hog/config.C
/nix/store/idmgv1qdd5hv81xqff45nlxzvjgvrq42-gcc-wrapper-5.5.0/bin/g++  -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -I/build/hobbes/include  -Werror=old-style-cast -Werror -Wall -Wextra -Winit-self -Wreturn-type -Wunused-variable -Wsign-compare -Warray-bounds -Wunknown-pragmas -Wuninitialized -Wstrict-aliasing -Wunused-value -Wunused-label -Wswitch -Wcast-align -Wctor-dtor-privacy -Wmissing-noreturn -Wunused-parameter -Wreorder   -std=gnu++11 -o CMakeFiles/hog.dir/bin/hog/stat.C.o -c /build/hobbes/bin/hog/stat.C
/nix/store/idmgv1qdd5hv81xqff45nlxzvjgvrq42-gcc-wrapper-5.5.0/bin/g++  -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -I/build/hobbes/include  -Werror=old-style-cast -Werror -Wall -Wextra -Winit-self -Wreturn-type -Wunused-variable -Wsign-compare -Warray-bounds -Wunknown-pragmas -Wuninitialized -Wstrict-aliasing -Wunused-value -Wunused-label -Wswitch -Wcast-align -Wctor-dtor-privacy -Wmissing-noreturn -Wunused-parameter -Wreorder   -std=gnu++11 -o CMakeFiles/hog.dir/bin/hog/netserver.C.o -c /build/hobbes/bin/hog/netserver.C
/nix/store/idmgv1qdd5hv81xqff45nlxzvjgvrq42-gcc-wrapper-5.5.0/bin/g++  -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -I/build/hobbes/include  -Werror=old-style-cast -Werror -Wall -Wextra -Winit-self -Wreturn-type -Wunused-variable -Wsign-compare -Warray-bounds -Wunknown-pragmas -Wuninitialized -Wstrict-aliasing -Wunused-value -Wunused-label -Wswitch -Wcast-align -Wctor-dtor-privacy -Wmissing-noreturn -Wunused-parameter -Wreorder   -std=gnu++11 -o CMakeFiles/hog.dir/bin/hog/recovery.C.o -c /build/hobbes/bin/hog/recovery.C
/build/hobbes/bin/hi/www.C: In function 'void hi::write(int, const char*)':
/build/hobbes/bin/hi/www.C:23:69: error: ignoring return value of 'ssize_t write(int, const void*, size_t)', declared with attribute warn_unused_result [-Werror=unused-result]
 void write(int fd, const char* s)        { ::write(fd, s, strlen(s)); }
                                                                     ^
/build/hobbes/bin/hi/www.C: In function 'void hi::write(int, const string&)':
/build/hobbes/bin/hi/www.C:24:76: error: ignoring return value of 'ssize_t write(int, const void*, size_t)', declared with attribute warn_unused_result [-Werror=unused-result]
 void write(int fd, const std::string& s) { ::write(fd, s.c_str(), s.size()); }
                                                                            ^
/build/hobbes/bin/hi/main.C: In function 'void hi::runProcess(const string&, std::ostream&)':
/build/hobbes/bin/hi/main.C:555:22: error: ignoring return value of 'int system(const char*)', declared with attribute warn_unused_result [-Werror=unused-result]
   system(cmd.c_str());
                      ^
/build/hobbes/bin/hog/batchsend.C: In member function 'void hog::BatchSendSession::stepFile()':
/build/hobbes/bin/hog/batchsend.C:318:62: error: ignoring return value of 'int link(const char*, const char*)', declared with attribute warn_unused_result [-Werror=unused-result]
         link(this->tempfilename.c_str(), pubfilename.c_str());
                                                              ^
cc1plus: all warnings being treated as errors
```

**Comment by thmzlt** [comment]
> I'm not sure if you can pull that branch, but now it has some kind of complaint about linking all of the LLVM libraries. I wonder if the nix script should be changed somehow (I've just blindly copy/pasted it to run with nix-build).

I also reached the linking issue (it couldn't lik to libLLVMsupport), and I was able to fix it by upgrading llvm to version 6 (replacing `llvm_35` with `llvm_6`) in the derivation.

I'm finally unstuck, and could finish writing the derivation. Here's the final version:

```
{ pkgs ? import (fetchTarball https://github.com/nixos/nixpkgs-channels/archive/nixos-unstable.tar.gz) {} }:

pkgs.stdenv.mkDerivation {
  name = "hobbes";
  src = ./.;

  nativeBuildInputs = with pkgs; [
    cmake
    gcc5
    llvm_6
    ncurses
    python27
    readline
    zlib
  ];
}
```

**Comment by thmzlt** [comment]
Fixed by #319.
