### PR TITLE
port hobbes to OSX

### PR DESCRIPTION
**Pull request by kthielen**
This adjusts various parts of the code so that it can also build on OSX.  In the process, I also fixed the bug where the std::string type didn't lift correctly (which has affected a couple of other platforms as well).

This change still leaves open the issue of supporting C++ class coercions on OSX because it seems that clang doesn't expose the same information that gcc does (at least in the clang build on my Mac).

Also readline seems to be a little buggy on OSX so the "hi" shell doesn't show the prompt consistently or support the line edit history correctly.

But at least the hobbes compiler works, all tests (except class coercion tests) pass, structured logging over shared memory works via storage.H and lightweight networking via net.H also works.

### CODE REVIEW

**Comment by baiyanhuang** [comment]
Hi, Kalani,

I tried all LLVM versions available on mac as below:
```
$ brew search llvm
llvm ✔                                       llvm@3.7 ✔                                   llvm@3.8 ✔                                   llvm@3.9 ✔
```

all failed with:

> CMake Error at /usr/local/opt/llvm@3.8/lib/llvm-3.8/share/llvm/cmake/LLVM-Config.cmake:203 (message):
>   Library `jit' not found in list of llvm libraries.

You may want to specify what exact environment is needed to have this build/test properly?

**Comment by kthielen** [comment]
I hit a similar issue when I was moving between different LLVM builds on OSX.  I am not sure what the best way is to select components here -- if I select "all" then I think I can get it to work across different LLVM versions but then it's going to link against too many things.

FWIW, I did all of my testing with llvm-3.5 as selected by the MacPorts package manager.

**Comment by libow** [comment]
I tried llvm37 (homebrew) + link all,  i can build it successfully, but cores when i running "hi".

**Comment by kthielen** [comment]
My tests here were only with LLVM 3.5.  I will take a look at 3.7, see if there's anything I can do to sort out the component selection between different versions.  If anybody has ideas about that, I'd love to know -- else I may put the question to one of the LLVM lists.

**Comment by kthielen** [comment]
It looks like this is an issue with LLVM, there doesn't seem to be a consistent way to select components for a JIT between 3.5-4: https://github.com/RPCS3/rpcs3/issues/1070

I think that we might need to add some analysis to our cmake file to select different components depending on which version of LLVM is selected.

**Comment by kthielen** [comment]
Updated PR, cmake will pull all LLVM components -- this is more than we need but it's not clear to me how to select just what's necessary between LLVM versions, hopefully the linker can sort this out.

Also I reproduced the crash with LLVM 3.7 on OSX.  It was an issue with some logic in jitcc specific to 3.7+ versions of LLVM.  It looks like "hi" works with these changes.

**Comment by baiyanhuang** [comment]
Now I saw this with llvm3.7:
```
In file included from /Users/huangbaiyan/work/hobbes/lib/hobbes/eval/func.H:6:
/Users/huangbaiyan/work/hobbes/lib/hobbes/lang/tylift.H:195:10: error: redefinition of 'hobbes::lift<std::string, true>'
  struct lift< std::string, true > { static MonoTypePtr type(typedb&) { return OpaquePtr::make("std::string", sizeof(std::string), true); }  };
```

Here is what I used to build:
```
export LLVM_DIR=/usr/local/opt/llvm@3.7/lib/llvm-3.7/share/llvm/cmake
cmake .
make
make install
```

**Comment by kthielen** [comment]
Bad merge, fixed now.

**Comment by kthielen** [comment]
I fixed another problem that I noticed with the LLVM 3.7 issue pointed out by libow.

**Comment by kthielen** [comment]
(PS: It seems that my OS system readline library is a little wonky, echoes the prompt the wrong way.  I had to update it.)

**Comment by jeb2239** [comment]
If no one else is having this problem than feel free to ignore this comment but this project doesn't build with xcode's clang. Specifically there is a complaint about `clock_gettime` which seems to be related to https://stackoverflow.com/questions/5167269/clock-gettime-alternative-in-mac-os-x 


```
jonathanbarrios@lasalle [19:40:55] [~/hobbes] [port-to-OSX *]
-> % make
Scanning dependencies of target hobbes
[  0%] Building CXX object CMakeFiles/hobbes.dir/lib/hobbes/boot/gen/boot.C.o
[  1%] Building CXX object CMakeFiles/hobbes.dir/lib/hobbes/db/bindings.C.o
[  1%] Building CXX object CMakeFiles/hobbes.dir/lib/hobbes/db/file.C.o
[  2%] Building CXX object CMakeFiles/hobbes.dir/lib/hobbes/db/series.C.o
In file included from /Users/jonathanbarrios/hobbes/lib/hobbes/db/series.C:2:
In file included from /Users/jonathanbarrios/hobbes/lib/hobbes/db/series.H:12:
/Users/jonathanbarrios/hobbes/lib/hobbes/util/perf.H:15:21: error: use of undeclared identifier 'CLOCK_MONOTONIC'
  if (clock_gettime(CLOCK_MONOTONIC, &ts) == 0) {
                    ^
/Users/jonathanbarrios/hobbes/lib/hobbes/util/perf.H:25:21: error: use of undeclared identifier 'CLOCK_REALTIME'
  if (clock_gettime(CLOCK_REALTIME, &ts) == 0) {
                    ^
2 errors generated.
make[2]: *** [CMakeFiles/hobbes.dir/lib/hobbes/db/series.C.o] Error 1
make[1]: *** [CMakeFiles/hobbes.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by kthielen** [comment]
@jeb2239 I wonder if this could be an issue with older XCode/clang installs?

My cmake-generated make files seem to decide on using this compiler from my local system (macOS Sierra 10.12.5):

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -> clang

Do you know what OS/XCode version you're using?

**Comment by jeb2239** [comment]
That must be it. I was using capitain. 

_Sent from my Motorola XT1650 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by baiyanhuang** [comment]
I uninstall my XCODE, and set CC to `export CC=/usr/local/opt/llvm@3.7/bin/clang-3.7,` but still got the same error as jeb2239 above.

**Comment by jeb2239** [comment]
Could this be a brew vs macports issue? 

_Sent from my Motorola XT1650 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by kthielen** [comment]
I'm using clang with, I think, a recent version of XCode.  This clock_gettime code isn't really that important so I would rather not have it block anybody.  If you stub the tick/time functions to just return 0, are you able to make progress or are there other compile errors?

**Comment by baiyanhuang** [comment]
There are a few other errors after comment out the tick/time error:

```
/Users/huangbaiyan/Dev/work/hobbes/lib/hobbes/util/autorelease.H:16:12: warning: reference to stack memory associated with local variable 'rs' returned [-Wreturn-stack-address]
    return rs;
           ^~
/Users/huangbaiyan/Dev/work/hobbes/lib/hobbes/util/autorelease.H:37:7: error: thread-local storage is not supported for the current target
      thread_local Vals vs;
```

What is the difference between using clang installed and clang from Xcode?

**Comment by kthielen** [comment]
Baiyan, what version of clang are you using?  I haven't seen those complaints about thread_local before, and the warning referencing the return of a stack address is on a thread_local var too (just double-checked).

**Comment by baiyanhuang** [comment]
I am using this version:

```
$ /usr/local/opt/llvm@3.7/bin/clang-3.7 --version
clang version 3.7.1 (tags/RELEASE_371/final)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
```

and my build is started with:
```
export LLVM_DIR=/usr/local/opt/llvm@3.7/lib/llvm-3.7/share/llvm/cmake
export CC=/usr/local/opt/llvm@3.7/bin/clang-3.7
cmake .
make
```

My llvm is installed using homebrew

**Comment by kthielen** [comment]
I previously was installing LLVM with ports but also used brew to get LLVM 3.7 and fix the issue that libow hit with 3.7.

I seem to be picking up this version of clang with my XCode install:

```
$ /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ --version
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

I am not sure whether hobbes can compile with clang 3.7.  That's probably another porting effort, but the complaints about thread_local scare me.  :)

**Comment by libow** [comment]
@baiyanhuang pls try osx10.12+ and xcode8.3 toolchain
